variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - test
  - build_test_push
  - deploy

test:
  image: python:alpine
  stage: test
  script:
    - cd app/image
    - pip install .
    - py.test

build_test_push_image:
  image: docker:19.03.5
  services:
    - docker:19.03.5-dind
  stage: build_test_push
  before_script:
    - docker info 
    - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
  script:
    - cd app/
    - docker build -t new_app_image .
    - docker run -e TESTING=TRUE new_app_image
    - echo $CI_COMMIT_SHORT_SHA
    - docker tag new_app_image "joelfreeman/aws-ecs-app:$(echo $CI_COMMIT_SHORT_SHA)"
    - docker push "joelfreeman/aws-ecs-app:$(echo $CI_COMMIT_SHORT_SHA)"

deploy-to-prod:
  image:
    name: silintl/ecs-deploy
    entrypoint: [""]
  stage: deploy
  before_script: 
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  script: /ecs-deploy -r ap-southeast-2 -c app-ecs-cluster -n aws-ecs-app -i joelfreeman/aws-ecs-app --tag-env-var CI_COMMIT_SHORT_SHA --enable-rollback --timeout 300