version: "3.7"
services:

  wiki:
    image: requarks/wiki:2
    restart: unless-stopped
    container_name: wiki
    environment:
      DB_TYPE: postgres
      DB_NAME: wikijs
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: changeme
    depends_on:
      - postgres
      - nginx

  wiki2:
    image: requarks/wiki:2
    restart: unless-stopped
    container_name: wiki2
    environment:
      DB_TYPE: postgres
      DB_NAME: wikijs
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: changeme
    depends_on:
      - postgres
      - nginx

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: nginx
    ports:
    - "443:443"
    - "80:80"
    volumes:
    - ./nginx-conf.conf:/etc/nginx/conf.d/default.conf
  
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    container_name: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: wikijs
      POSTGRES_USER: postgres
