version: "3.7"
services:
  flask:
    build: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASS: pass
      POSTGRES_HOST: postgres
      POSTGRES_DB: postgres
      CONFIG: 'development'
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: pass

      
      