version: "3.7"
services:
  flask:
    build: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASS: pass
      POSTGRES_HOST: postgres
      POSTGRES_DB: postgres
      CONFIG: developmentConfig
      CREATE_DB: "true"
    ports:
      - "5000:5000"
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: pass