version: '3.7'

services:
   db:
    image: mariadb:latest
    restart: unless-stopped
    environment: 
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DB: wordpress

   wordpress:
     depends_on:
       - db
     build:
      context: image/.
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       BUCKET_NAME: bruh
       AWS_REGION: ap-southeast-2